### ISSUE TITLE
Error 404 or 403 redirects to the HTML template instead of the configured PID

### ISSUE THREAD

**Issue by angeloprevitali** [aaw-team/pagenotfoundhandling#5]
If in the list > root Domain configuration the Error 404 handling is activated and set up to the corresponding 404 and 403 pages (normal TYPO3 pages) the EXT:pagenotfoundhandling redirects always to the HTML template as specified in the EM instead of the corresponding PIDs set.

We do use TYPO3 version 8.7.13 and the EXT:pagenotfoundhandling version 2.4.6.
We didin't configured nothing in the Install Tool concerning the error handler. 

Any hint? 

Thanks in advance.

Best regards,
Angelo

**Comment by christianfutterlieb** [comment]
Hi Angelo

I wrote a new [troubleshooting page](https://github.com/aaw-team/pagenotfoundhandling/wiki/Troubleshooting) in the wiki, please check that out first. If you resolve your problems yourself, please close this issue

**Comment by angeloprevitali** [comment]
Hello Christian

i did all that what you wrote in your wiki but without success. But now i think I found something interesting about this error: The reason is because the website i am testing is password protected by .htaccess with username and password from apache side. So it needs some credientals with a prompt coming. I removed those but also without any success. 

The single page with the error message can be called up without problem.

BUT what i saw now is from the default HTML layout (as you wrote that is used as a fallback) in this one in the debug mode there is the following coming red marked:

![screenshot](https://user-images.githubusercontent.com/17588253/41907277-ab773efa-7940-11e8-901b-cea39cd2f1c5.png)

Can that be that the result of the error 404 handling is an header response of 401? Could that be maybe a problem? If so, how to solve it?

I think that if you logged in into a .pwd-protected website the credientials are given - so i got access to get shown the error 404 page from the TYPO3. May there be another thing somewhere hidden in the extension?

If I think like you wrote the HTML file is just a fallback in case the PID could not be called up. BUT THE PID of the error page CAN be called up! So why can the extension not just call up the corresponding PID page from the TYPO3? Should work but it doesn't...

Any ideas?

Regards,
Angelo

**Comment by angeloprevitali** [comment]
Remarks: Could that be that your extension gets NO credientials to call up the correct error 404 page defined in TYPO3 because of missing credientials of your extension?

**Comment by christianfutterlieb** [comment]
Hi Angelo

> So it needs some credientals with a prompt coming. I removed those but also without any success.
> The single page with the error message can be called up without problem.
> [...]
> BUT THE PID of the error page CAN be called up!

Have you really confirmed that `$url` works correctly by logging into the server via ssh and using `wget`, `curl` or some other tool that can make HTTP requests? Important note: **do not try to do this in your browser!** The request MUST be made from the server to the server.

Maybe your problem could be resolved when you enable `http.sendXForwardedForHeader` in Extension Manager configuration. With this option enabled, pnfh will send the `X-Forwarded-For` HTTP header, which could in turn satisfy your configured access restrictions.

Btw: if you use plain basic auth without any further restrictions other than `valid-user` (or alike), the 404 page will work, because pnfh proxies the `Authorization` header (which does not seem to be the case in you screenshot). If you still use digest authentication, you can configure your credentials in `http.digestAuthentication`.

**Comment by angeloprevitali** [comment]
We seemed to found the problem of the Extension: We work on a LINUX PLESK envoirement. And by setting up a password protection to the whole website it looks like the PLESK changes something in the configuration we do not know exactly. Before we set up the password protection it worked prefectly. So i will close this ticket due to i think it is not anymore a extension based problem.

Thanks for help. 

Regards,
Angelo
