### ISSUE TITLE
Language guessing not working

### ISSUE THREAD

**Issue by angeloprevitali** [aaw-team/pagenotfoundhandling#7]
On a multilanguage website the page redirect to the corresponding translated error 404 page in TYPO3 isn't working. There is always the "Default" language coming. By uninstalling the EXT and using the configuration of the site > config in the YAML file it works well.

TYPO3: 9.5.7
OS: Linux
EXT: pagenotfoundhandling: 2.5.1

**Comment by christianfutterlieb** [comment]
Thx for your report. Can you please test the fix in branch 2_5 and confirm. Then, I'll release the fix this afternoon

**Comment by angeloprevitali** [comment]
Hi Christian

thanks for your quick fixing. It works now perfect. But there are three small things that aren't correct now:

1. In the tab of the list > page > Domain > Page not found handling the tab message says "Errorhandling (DEPRECATED) That shouldn't be, right?

2. By installing the revised EXT there has to be done a DB compare which is not done by the update:

`CREATE TABLE `tx_pagenotfoundhandling_history` (`uid` INT UNSIGNED AUTO_INCREMENT NOT NULL, `time` INT UNSIGNED DEFAULT 0 NOT NULL, `site_identifier` VARCHAR(255) DEFAULT NULL, `status_code` SMALLINT UNSIGNED DEFAULT 0 NOT NULL, `failure_reason` VARCHAR(255) DEFAULT NULL, `request_uri` VARCHAR(1024) DEFAULT '' NOT NULL, `referer_uri` VARCHAR(1024) DEFAULT '' NOT NULL, `user_agent` VARCHAR(1024) DEFAULT '' NOT NULL, PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB`

and just something else (just an info): Wouldn't it be a good idea, if someone added manually in the site config the Error 404 that by installing the EXT the lines would be deleted. Otherwise on a 9.5 the EXT will not work.

Thanks.

Regards,
Angelo

**Comment by christianfutterlieb** [comment]
Hi @angeloprevitali 

I think you got some things wrong there. Most likely you checked on master rather than the 2_5 branch. In master the development for version 3.x goes on, in which the current configuration style (extension manager and/or sys_domain record) are deprecated functionality; thus the label in sys_domain TCA. Furthermore, there will be a history for error page calls and a backend module that shows them, that's what the db table is for.

To test the correct branch run for example:

    git fetch
    git checkout -b 2_5 origin/2_5

> and just something else (just an info): Wouldn't it be a good idea, if someone added manually in the site config the Error 404 that by installing the EXT the lines would be deleted. Otherwise on a 9.5 the EXT will not work.

As of version 3.x the TYPO3 Site Configuration is the new main entry point for pagenotfoundhandling and the configuration lives in the site's config.yaml file. You're welcome to test the current master in a TYPO3 v9 ;-)

For the moment (pnfh v2.5) there is a hint in the documentation not to use the TYPO3 Site Configuration's errorHandling: https://docs.typo3.org/p/aaw-team/pagenotfoundhandling/2.5/en-us/Administration/Index.html#installation

**Comment by christianfutterlieb** [comment]
> By installing the revised EXT there has to be done a DB compare which is not done by the update

Hint: when you change an extension's code with git (rather than updating the normal way), you can't expect the db (or other configs) to get updated. To be on the 'safe' side, you can uninstall and reinstall the extension right after every code change.

**Comment by angeloprevitali** [comment]
Hi @christianfutterlieb 

I do install everything without composer or so.

Thanks. I was completely wrong! You are right. Everything works now in version 2.5.2-dev as it should. Apart of the config.yaml-file of the site: There is still the following code 

`errorHandling: {  }`

There is nothing inside the {}... And even on the whole other code lines i don't find any configuration. But it works.

**Comment by christianfutterlieb** [comment]
> Everything works now in version 2.5.2-dev as it should

Cool, I'll release v2.5.2 in a moment.

> There is still the following code
>     errorHandling: { }
> There is nothing inside the {}.

That's fine.

> And even on the whole other code lines i don't find any configuration

As I wrote: pagenotfoundhandling v2.5.x does **not** use Site Configuration at all. Only as of version 3.x (which is not yet released) it will. So you most probably experience a little mess since you checked out master. Just save the Site Configuration once again in the Backend an you'll be fine, TYPO3 only handles known options.

**Comment by angeloprevitali** [comment]
Thanks @christianfutterlieb 

I think today is too hot to work to be concentrated... ;-)

Regards, Angelo

**Comment by christianfutterlieb** [comment]
.. and the worst is yet to come :o

cheers!
