### ISSUE TITLE
Difference between this extension and TYPO3 9.5 Site Configuration Error Handling

### ISSUE THREAD

**Issue by dkoether** [aaw-team/pagenotfoundhandling#8]
Hello everyone,

I came across this extension in a TYPO3 project and for me its not clear what the differences between this extension and the site configurations error handling in TYPO3 9 are. I already checked the documentation of this extension but it seems to achieve the same as the built-in function of TYPO3 9. Can somebody explain the features of this extension please?

Thanks in advance!

**Comment by christianfutterlieb** [comment]
Hi @dkoether 

Thanks for your question, I'll try to clarify.

The TYPO3 built-in error handling is equipped with multiple useful possibilities to display contents in case of an error. The (in my opinion) easiest way to configure an error page is to display the contents of a page from the page tree. This is already possible with the built-in handler ("Show Content from Page"). So far so good.

But if you have different requirements than just fetching the error page's contents, you're stuck, and your only possibility is to add an own implementation. And that's where pnfh comes into play. These are the main features of pnfh (some are in v3 only):

* Add some special GET param(s) when fetching the error page (including a substitution for the requested URL)
* Handle multi-language systems
* Handle authenticated requests (logged in fe_users and/or HTTP Authentication [eg. the .htaccess password])
* Prevent endless loops when requesting error pages
* Record statistical data about what URLs are requested
* Tools for developers:
   * Write logs
   * Show debug data
   * Disable TLS-certificate verification (very handy on local development systems with self-signed certs)

The development of version 3 is still in progress and the documentation does not reflect the changes since 2.x yet. You're very welcome to check out the current state in master and leave your feedback.

Cheers, Christian

**Comment by dkoether** [comment]
Thank you @christianfutterlieb for this extensively explanation and fast answer! :)
